je_user_users:
    pattern:  /{page}
    defaults: { _controller: ApplicationSonataUserBundle:User:index, page: 1 }
    requirements:
        page: \d+

je_user_users_new:
    pattern:  /new
    defaults: { _controller: ApplicationSonataUserBundle:User:new }

je_user_users_edit:
    pattern:  /{id}/edit
    defaults: { _controller: ApplicationSonataUserBundle:User:edit }
    requirements:
        id: \d+

je_user_users_profile:
    pattern:  /{id}/profile
    defaults: { _controller: ApplicationSonataUserBundle:User:profile }
    requirements:
        id: \d+

je_user_users_delete:
    pattern:  /{id}/delete
    defaults: { _controller: ApplicationSonataUserBundle:User:delete }
    requirements:
        id: \d+

je_user_users_delete_confirmation:
    pattern:  /{id}/delete-confirmation
    defaults: { _controller: ApplicationSonataUserBundle:User:deleteConfirmation }
    requirements:
        id: \d+
