junior_esiee_page_homepage:
    path:     /hello/{name}
    defaults: { _controller: JuniorEsieePageBundle:Default:index }

page_contact:
    pattern : /contactez-nous
    defaults: { _controller: JuniorEsieePageBundle:Page:contact } 

page_apropos:
    pattern : /a-propos
    defaults: { _controller: JuniorEsieePageBundle:Page:about } 

page_prestations:
    pattern : /nos-prestations
    defaults: { _controller: JuniorEsieePageBundle:Page:prestations } 

page_accueil:
    pattern : /
    defaults: { _controller: JuniorEsieePageBundle:Page:index } 

page_appeloffre:
    pattern : /appel-offre
    defaults: { _controller: JuniorEsieePageBundle:Page:appeloffre } 

page_mentions:
    pattern : /mentions-legales
    defaults: { _controller: JuniorEsieePageBundle:Page:mentions } 

page_presse:
    pattern : /presse
    defaults: { _controller: JuniorEsieePageBundle:Page:presse } 	