imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        version: %application_version%
    form:
        resources:
            - 'SonataAdminBundle:Form:silex_form_div_layout.html.twig'
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'SonataUserBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - JuniorEsieePageBundle
    #java: /usr/bin/java
    read_from:      "%kernel.root_dir%/../www"
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        lessphp:
            apply_to: "\.less$"
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            formatter: "compressed"
            preserve_comments: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_admin:
    title:      JE Inside
    title_logo: logo.png
    templates:
        layout:  ApplicationSonataAdminBundle::layout.html.twig
    dashboard:
        blocks:
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Coucou</h2>
                        <p>Tvvmb ?</p>
            -
                position: left
                type: sonata.admin.block.admin_list
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin_doctrine_orm.block.audit:
            contexts:   [admin]
        sonata.user.block.menu:
        sonata.user.block.account:
        sonata.admin.block.search_result:
        sonata.block.service.text:
        application.sonata.block.service.editable_text:

sonata_user:
    security_acl: true
    manager_type: orm
    admin:
        user:
            class:       Application\Sonata\UserBundle\Admin\UserAdmin
            translation: ApplicationSonataUserBundle

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

ivory_ck_editor:
    default_config: main
    configs:
        main:
            toolbar: "toolbar_basic"
            allowedContent: true
            # protectedSource: ['/<i[^>]*><\/i>/g']
            contentsCss: ['/bundles/ivoryckeditor/contents.css', '/bundles/junioresieepage/css/font-awesome.css', '/bundles/junioresieepage/css/bootstrap.min.css']
    toolbars:
        configs:
            toolbar_basic: ["@clipboard", "@editing", "/", "@basicstyles", "@links", "@paragraph", "/", '@styles', '@colors', '@tools', '@insert' ]
        items:
            clipboard : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo', '-', 'Preview' ]
            editing : [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ]

            basicstyles : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ]
            paragraph : [ 'NumberedList','BulletedList','-','Blockquote','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ]
            links: [ 'Link','Unlink','Anchor' ]
            insert : [ 'Image', 'Table','HorizontalRule','SpecialChar' ]

            styles : [ 'Format','FontSize' ]
            colors : [ 'TextColor','BGColor' ]
            tools : [ 'Source', 'Maximize' ]

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions

sonata_media:
    class:
        media:             Application\Sonata\MediaBundle\Entity\Media
        gallery:           Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                big:   { width: 500 , quality: 90}
                small: { width: 90 , quality: 95}
        attachment:
            providers:
                - sonata.media.provider.file

            formats:
                big:   { width: 500 , quality: 90}
                small: { width: 90 , quality: 95}

    cdn:
        server:
            path: %hostname%/uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../www/uploads/media
            create:     false
