junior_esiee_notification:
    resource: "@JuniorEsieeNotificationBundle/Resources/config/routing.yml"
    prefix:   /

junior_esiee_stat:
    resource: "@JuniorEsieeStatBundle/Resources/config/routing.yml"
    prefix:   /stats

junior_esiee_finances:
    resource: "@JuniorEsieeFinancesBundle/Resources/config/routing.yml"
    prefix:   /finances

junior_esiee_business:
    resource: "@JuniorEsieeBusinessBundle/Resources/config/routing.yml"
    prefix:   /project

junior_esiee_page:
    resource: "@JuniorEsieePageBundle/Resources/config/routing.yml"
    prefix:   /

application_sonata_user:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/routing.yml"
    prefix:   /team

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
