JuniorEsiee\BusinessBundle\Entity\Project:
    type: entity
    table: je_project
    repositoryClass: JuniorEsiee\BusinessBundle\Repository\ProjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        clientLastName:
            type: string
            length: 255
            column: client_last_name
        clientFirstName:
            type: string
            length: 255
            column: client_first_name
        clientCompany:
            type: string
            length: 255
            column: client_company
            nullable: true
        clientPhone:
            type: string
            length: 20
            column: client_phone
            nullable: true
        clientEmail:
            type: string
            length: 255
            column: client_email
            nullable: true
        clientAddress:
            type: string
            length: 255
            column: client_address
            nullable: true
        clientZipCode:
            type: string
            length: 255
            column: client_zip_code
            nullable: true
        clientCity:
            type: string
            length: 255
            column: client_city
            nullable: true
        depositDate:
            type: date
            column: deposit_date
        title:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        delay:
            type: date
            nullable: true
        state:
            type: string
            length: 255
            nullable: true
        commercialEnrollmentOpen:
            type: boolean
            length: 255
            nullable: false
        studentsEnrollmentOpen:
            type: boolean
            length: 255
            nullable: false
    manyToMany:
        students:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            nullable: true
            joinTable:
                name: je_project__students
                joinColumns:
                    project_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
        skills:
            targetEntity: Application\Sonata\UserBundle\Entity\Skill
            nullable: true
            joinTable:
                name: je_project__skills
                joinColumns:
                    project_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    skill_id:
                        referencedColumnName: id
        skillCategories:
            targetEntity: Application\Sonata\UserBundle\Entity\SkillCategory
            nullable: true
            joinTable:
                name: je_project__skill_categories
                joinColumns:
                    project_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    skill_category_id:
                        referencedColumnName: id
        studentsApplicants:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            nullable: true
            joinTable:
                name: je_project__students_applicants
                joinColumns:
                    project_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
        commercialApplicants:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            nullable: true
            joinTable:
                name: je_project__commercial_applicants
                joinColumns:
                    project_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
    manyToOne:
        commercial:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            nullable: true
        rbu:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            nullable: true
    oneToOne:
        scopeStatement:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            joinColumn:
                nullable: true
            cascade: ["all"]
        graphicCharter:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            joinColumn:
                nullable: true
            cascade: ["all"]
    lifecycleCallbacks: {  }
