JuniorEsiee\BusinessBundle\Entity\Project:
    type: entity
    table: null
    repositoryClass: JuniorEsiee\BusinessBundle\Repository\ProjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        clientLastName:
            type: string
            length: 255
            column: client_last_name
        clientFirstName:
            type: string
            length: 255
            column: client_first_name
        clientCompany:
            type: string
            length: 255
            column: client_company
        clientPhone:
            type: string
            length: 20
            column: client_phone
        clientEmail:
            type: string
            length: 255
            column: client_email
        clientAddress:
            type: string
            length: 255
            column: client_address
        clientZipCode:
            type: string
            length: 255
            column: client_zip_code
        clientCity:
            type: string
            length: 255
            column: client_city
        depositDate:
            type: date
            column: deposit_date
        title:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        delay:
            type: date
            nullable: true
        state:
            type: array
    manyToMany:
        students:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            nullable: true
        skills:
            targetEntity: Application\Sonata\UserBundle\Entity\Skill
            nullable: true
        skillCategories:
            targetEntity: Application\Sonata\UserBundle\Entity\SkillCategory
            nullable: true
    manyToOne:
        commercial:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            nullable: true
        rbu:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            nullable: true
    oneToOne:
        scopeStatement:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            joinColumn:
                nullable: true
            cascade: ["all"]
        graphicCharter:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            joinColumn:
                nullable: true
            cascade: ["all"]
    lifecycleCallbacks: {  }
