je_home_index:
    pattern : /
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:index }

je_business_my_project:
    pattern : /my-project/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:myProject, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_inbox:
    pattern : /inbox/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:inbox, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_new:
    pattern : /new 
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:new }

je_events_temporary:
    pattern : /events
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:myProject, page: 1 }

je_business_project_edit:
    pattern : /{id}/edit
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:edit }
    requirements:
        id: \d+

je_business_project_show:
    pattern : /{id}/show
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:show }
    requirements:
        id: \d+

je_business_project_delete_confirmation:
    pattern : /{id}/delete-confirmation
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:deleteConfirmation }
    requirements:
        id: \d+

je_business_project_delete:
    pattern : /{id}/delete
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:delete }
    requirements:
        id: \d+
