je_home_index:
    pattern : /
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:index }

je_business_my_project:
    pattern : /mes-ap/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:myProject, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_new: # nom de la route
    pattern : /ap/new    # schéma de l'URL
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:new }

je_events_temporary:
    pattern : /events
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:myProject, page: 1 }

je_business_project_edit:
    pattern : /ap/{id}/edit
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:edit }
    requirements:
        id: \d+

je_business_project_show:
    pattern : /ap/{id}/show
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:show }
    requirements:
        id: \d+

je_business_project_delete_confirmation:
    pattern : /ap/{id}/delete-confirmation
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:deleteConfirmation }
    requirements:
        id: \d+

je_business_project_delete:
    pattern : /ap/{id}/delete
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:delete }
    requirements:
        id: \d+
