je_home_index:
    pattern : /
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:index }

je_business_my_project:
    pattern : /my-project/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:myProject, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_inbox:
    pattern : /inbox/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:inbox, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_in_progress:
    pattern : /in-progress/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:inProgress, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_waiting_commercial:
    pattern : /waiting-commercial/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:waitingCommercial, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_waiting_students:
    pattern : /waiting-students/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:waitingStudents, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_waiting_information:
    pattern : /waiting-information/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:waitingInformation, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_aborted:
    pattern : /aborted/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:aborted, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_closed:
    pattern : /closed/{page}/{sort}/{direction}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:closed, page: 1, sort: p.depositDate, direction: desc }
    requirements:
        page: \d+
        sort: p\.[^/]+
        direction: asc|desc

je_business_project_new:
    pattern : /new 
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:new }

je_events_temporary:
    pattern : /events
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:myProject, page: 1 }

je_business_project_edit:
    pattern : /{id}/edit
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:edit }
    requirements:
        id: \d+

je_business_project_show:
    pattern : /{id}/show
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:show }
    requirements:
        id: \d+

je_business_project_validate:
    pattern : /{id}/validate
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:validate }
    requirements:
        id: \d+

je_business_project_delete_confirmation:
    pattern : /{id}/delete-confirmation
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:deleteConfirmation }
    requirements:
        id: \d+

je_business_project_delete:
    pattern : /{id}/delete
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:delete }
    requirements:
        id: \d+

je_business_project_abort_confirmation:
    pattern : /{id}/abort-confirmation
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:abortConfirmation }
    requirements:
        id: \d+

je_business_project_abort:
    pattern : /{id}/abort
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:abort }
    requirements:
        id: \d+

je_business_project_close_confirmation:
    pattern : /{id}/close-confirmation
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:closeConfirmation }
    requirements:
        id: \d+

je_business_project_close:
    pattern : /{id}/close
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:close }
    requirements:
        id: \d+

je_business_project_open_enrollment:
    pattern : /{id}/open-enrollment/{type}/{open}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:openEnrollment, type: implementer, open: 1 }
    requirements:
        id: \d+
        type: commercial|implementer
        open: 1|0

je_business_project_postulate:
    pattern : /{id}/postulate/{type}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:postulate, type: implementer }
    requirements:
        id: \d+
        type: commercial|implementer

je_business_project_chose_candidate:
    pattern : /{id}/chose-candidate/{type}/{candidate}/{accept}
    defaults: { _controller: JuniorEsieeBusinessBundle:Project:choseCandidate, type: implementer }
    requirements:
        id: \d+
        type: commercial|implementer
        candidate: \d+
        accept: accept|decline
