JuniorEsiee\BusinessBundle\Entity\Project:
    properties:
        clientLastName:
            - NotBlank: ~
        # clientFirstName:
        #     - NotBlank: ~
        clientPhone:
            # - NotBlank: ~
            - Length:
                max: 20
        clientEmail:
            # - NotBlank: ~
            - Email:
                message: "'{{ value }}' n'est pas un email valide."
        # clientAddress:
        #     - NotBlank: ~
        # clientZipCode:
        #     - NotBlank: ~
        # clientCity:
        #     - NotBlank: ~
        depositDate:
            - DateTime: ~
        delay:
            - DateTime: ~
        state:
            - Choice: { callback: getStates }
        # skillCategories:
        #     - Count:
        #         min: 1
        #         minMessage: "Vous devez définir au minimum une majeur."
        # rbu:
        #     - NotBlank:
        #         message: "Vous devez définir le RBU."
