parameters:

services:
    application.sonata.user.admin.user:
        class: Application\Sonata\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs",  label_catalogue:"ApplicationSonataUserBundle", label_translator_strategy:"sonata.admin.label.strategy.underscore", label: "Utilisateurs" }
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\User
            - ~
        calls:
            - [ setUserManager, [@fos_user.user_manager]]
            - [ setTranslationDomain, [%sonata.user.admin.user.translation_domain%]]
            - [ setTokenGenerator, [@fos_user.util.token_generator]]
            - [ setMailer, [@application.sonata.user.mailer]]
            - [ setLogger, [@logger]]
    application.sonata.user.mailer:
        class: Application\Sonata\UserBundle\Mailer\Mailer
        public: false
        arguments:
            - @mailer
            - @router
            - @templating
            - { confirmation.template: '%fos_user.registration.confirmation.template%', resetting.template: '%fos_user.resetting.email.template%', from_email: {confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email%} }
